// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: cart/cart.proto

package cartpb

import (
	itempb "github.com/sedeotech/backend-interview/pkg/rpc/itempb"
	typepb "github.com/sedeotech/backend-interview/pkg/rpc/typepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid          string                    `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserUuid      string                    `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Entries       []*CartMsg_EntryMsg       `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	Configuration *CartMsg_ConfigurationMsg `protobuf:"bytes,4,opt,name=configuration,proto3" json:"configuration,omitempty"`
	PriceTotal    float64                   `protobuf:"fixed64,5,opt,name=price_total,json=priceTotal,proto3" json:"price_total,omitempty"`
	Created       *timestamppb.Timestamp    `protobuf:"bytes,40,opt,name=created,proto3" json:"created,omitempty"`
	Updated       *timestamppb.Timestamp    `protobuf:"bytes,41,opt,name=updated,proto3" json:"updated,omitempty"`
}

func (x *CartMsg) Reset() {
	*x = CartMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_cart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartMsg) ProtoMessage() {}

func (x *CartMsg) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartMsg.ProtoReflect.Descriptor instead.
func (*CartMsg) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{0}
}

func (x *CartMsg) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *CartMsg) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *CartMsg) GetEntries() []*CartMsg_EntryMsg {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *CartMsg) GetConfiguration() *CartMsg_ConfigurationMsg {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *CartMsg) GetPriceTotal() float64 {
	if x != nil {
		return x.PriceTotal
	}
	return 0
}

func (x *CartMsg) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *CartMsg) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.Updated
	}
	return nil
}

type CartGetMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *CartGetMsg) Reset() {
	*x = CartGetMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_cart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartGetMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartGetMsg) ProtoMessage() {}

func (x *CartGetMsg) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartGetMsg.ProtoReflect.Descriptor instead.
func (*CartGetMsg) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{1}
}

func (x *CartGetMsg) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type CartGetResultMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *CartMsg `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CartGetResultMsg) Reset() {
	*x = CartGetResultMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_cart_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartGetResultMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartGetResultMsg) ProtoMessage() {}

func (x *CartGetResultMsg) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartGetResultMsg.ProtoReflect.Descriptor instead.
func (*CartGetResultMsg) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{2}
}

func (x *CartGetResultMsg) GetResult() *CartMsg {
	if x != nil {
		return x.Result
	}
	return nil
}

type CartConfigureAddressMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartUuid string             `protobuf:"bytes,1,opt,name=cart_uuid,json=cartUuid,proto3" json:"cart_uuid,omitempty"`
	Address  *typepb.AddressMsg `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *CartConfigureAddressMsg) Reset() {
	*x = CartConfigureAddressMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_cart_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartConfigureAddressMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartConfigureAddressMsg) ProtoMessage() {}

func (x *CartConfigureAddressMsg) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartConfigureAddressMsg.ProtoReflect.Descriptor instead.
func (*CartConfigureAddressMsg) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{3}
}

func (x *CartConfigureAddressMsg) GetCartUuid() string {
	if x != nil {
		return x.CartUuid
	}
	return ""
}

func (x *CartConfigureAddressMsg) GetAddress() *typepb.AddressMsg {
	if x != nil {
		return x.Address
	}
	return nil
}

type CartConfigureResultMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *CartMsg `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CartConfigureResultMsg) Reset() {
	*x = CartConfigureResultMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_cart_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartConfigureResultMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartConfigureResultMsg) ProtoMessage() {}

func (x *CartConfigureResultMsg) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartConfigureResultMsg.ProtoReflect.Descriptor instead.
func (*CartConfigureResultMsg) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{4}
}

func (x *CartConfigureResultMsg) GetResult() *CartMsg {
	if x != nil {
		return x.Result
	}
	return nil
}

type CartAddItemMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartUuid string `protobuf:"bytes,1,opt,name=cart_uuid,json=cartUuid,proto3" json:"cart_uuid,omitempty"`
	ItemUuid string `protobuf:"bytes,2,opt,name=item_uuid,json=itemUuid,proto3" json:"item_uuid,omitempty"`
	Quantity int32  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *CartAddItemMsg) Reset() {
	*x = CartAddItemMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_cart_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartAddItemMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartAddItemMsg) ProtoMessage() {}

func (x *CartAddItemMsg) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartAddItemMsg.ProtoReflect.Descriptor instead.
func (*CartAddItemMsg) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{5}
}

func (x *CartAddItemMsg) GetCartUuid() string {
	if x != nil {
		return x.CartUuid
	}
	return ""
}

func (x *CartAddItemMsg) GetItemUuid() string {
	if x != nil {
		return x.ItemUuid
	}
	return ""
}

func (x *CartAddItemMsg) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CartAddItemResultMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *CartMsg `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CartAddItemResultMsg) Reset() {
	*x = CartAddItemResultMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_cart_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartAddItemResultMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartAddItemResultMsg) ProtoMessage() {}

func (x *CartAddItemResultMsg) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartAddItemResultMsg.ProtoReflect.Descriptor instead.
func (*CartAddItemResultMsg) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{6}
}

func (x *CartAddItemResultMsg) GetResult() *CartMsg {
	if x != nil {
		return x.Result
	}
	return nil
}

type CartUpdateQuantityMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartUuid string `protobuf:"bytes,1,opt,name=cart_uuid,json=cartUuid,proto3" json:"cart_uuid,omitempty"`
	ItemUuid string `protobuf:"bytes,2,opt,name=item_uuid,json=itemUuid,proto3" json:"item_uuid,omitempty"`
	Quantity int32  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *CartUpdateQuantityMsg) Reset() {
	*x = CartUpdateQuantityMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_cart_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartUpdateQuantityMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartUpdateQuantityMsg) ProtoMessage() {}

func (x *CartUpdateQuantityMsg) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartUpdateQuantityMsg.ProtoReflect.Descriptor instead.
func (*CartUpdateQuantityMsg) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{7}
}

func (x *CartUpdateQuantityMsg) GetCartUuid() string {
	if x != nil {
		return x.CartUuid
	}
	return ""
}

func (x *CartUpdateQuantityMsg) GetItemUuid() string {
	if x != nil {
		return x.ItemUuid
	}
	return ""
}

func (x *CartUpdateQuantityMsg) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CartUpdateQuantityResultMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *CartMsg `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CartUpdateQuantityResultMsg) Reset() {
	*x = CartUpdateQuantityResultMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_cart_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartUpdateQuantityResultMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartUpdateQuantityResultMsg) ProtoMessage() {}

func (x *CartUpdateQuantityResultMsg) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartUpdateQuantityResultMsg.ProtoReflect.Descriptor instead.
func (*CartUpdateQuantityResultMsg) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{8}
}

func (x *CartUpdateQuantityResultMsg) GetResult() *CartMsg {
	if x != nil {
		return x.Result
	}
	return nil
}

type CartEmptyMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartUuid string `protobuf:"bytes,1,opt,name=cart_uuid,json=cartUuid,proto3" json:"cart_uuid,omitempty"`
}

func (x *CartEmptyMsg) Reset() {
	*x = CartEmptyMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_cart_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartEmptyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartEmptyMsg) ProtoMessage() {}

func (x *CartEmptyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartEmptyMsg.ProtoReflect.Descriptor instead.
func (*CartEmptyMsg) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{9}
}

func (x *CartEmptyMsg) GetCartUuid() string {
	if x != nil {
		return x.CartUuid
	}
	return ""
}

type CartEmptyResultMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *CartMsg `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CartEmptyResultMsg) Reset() {
	*x = CartEmptyResultMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_cart_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartEmptyResultMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartEmptyResultMsg) ProtoMessage() {}

func (x *CartEmptyResultMsg) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartEmptyResultMsg.ProtoReflect.Descriptor instead.
func (*CartEmptyResultMsg) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{10}
}

func (x *CartEmptyResultMsg) GetResult() *CartMsg {
	if x != nil {
		return x.Result
	}
	return nil
}

type CartMsg_EntryMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item     *itempb.ItemMsg `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Quantity int32           `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *CartMsg_EntryMsg) Reset() {
	*x = CartMsg_EntryMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_cart_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartMsg_EntryMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartMsg_EntryMsg) ProtoMessage() {}

func (x *CartMsg_EntryMsg) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartMsg_EntryMsg.ProtoReflect.Descriptor instead.
func (*CartMsg_EntryMsg) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CartMsg_EntryMsg) GetItem() *itempb.ItemMsg {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *CartMsg_EntryMsg) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CartMsg_ConfigurationMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address *typepb.AddressMsg `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *CartMsg_ConfigurationMsg) Reset() {
	*x = CartMsg_ConfigurationMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_cart_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartMsg_ConfigurationMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartMsg_ConfigurationMsg) ProtoMessage() {}

func (x *CartMsg_ConfigurationMsg) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartMsg_ConfigurationMsg.ProtoReflect.Descriptor instead.
func (*CartMsg_ConfigurationMsg) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CartMsg_ConfigurationMsg) GetAddress() *typepb.AddressMsg {
	if x != nil {
		return x.Address
	}
	return nil
}

var File_cart_cart_proto protoreflect.FileDescriptor

var file_cart_cart_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x61, 0x72, 0x74, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x63, 0x61, 0x72, 0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x69, 0x74,
	0x65, 0x6d, 0x2f, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xca, 0x03,
	0x0a, 0x07, 0x43, 0x61, 0x72, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x07, 0x65, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61,
	0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x4d, 0x73, 0x67, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x44, 0x0a, 0x0d,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x4d,
	0x73, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x73, 0x67, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x34, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x28,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x34, 0x0a, 0x07, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x29, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x1a,
	0x49, 0x0a, 0x08, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x21, 0x0a, 0x04, 0x69,
	0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x69, 0x74, 0x65, 0x6d,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x73, 0x67, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x1a,
	0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x1a, 0x3e, 0x0a, 0x10, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x2a,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4d, 0x73,
	0x67, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x20, 0x0a, 0x0a, 0x43, 0x61,
	0x72, 0x74, 0x47, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x10,
	0x43, 0x61, 0x72, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x73, 0x67,
	0x12, 0x25, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x4d, 0x73, 0x67, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x62, 0x0a, 0x17, 0x43, 0x61, 0x72, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4d,
	0x73, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x72, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12,
	0x2a, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4d,
	0x73, 0x67, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x3f, 0x0a, 0x16, 0x43,
	0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x25, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72,
	0x74, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x66, 0x0a, 0x0e,
	0x43, 0x61, 0x72, 0x74, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x73, 0x67, 0x12, 0x1b,
	0x0a, 0x09, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x61, 0x72, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69,
	0x74, 0x65, 0x6d, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x74, 0x65, 0x6d, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x22, 0x3d, 0x0a, 0x14, 0x43, 0x61, 0x72, 0x74, 0x41, 0x64, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x25, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63,
	0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x6d, 0x0a, 0x15, 0x43, 0x61, 0x72, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x61, 0x72, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x61, 0x72, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x74, 0x65,
	0x6d, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x74,
	0x65, 0x6d, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x22, 0x44, 0x0a, 0x1b, 0x43, 0x61, 0x72, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x73,
	0x67, 0x12, 0x25, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x4d, 0x73, 0x67,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2b, 0x0a, 0x0c, 0x43, 0x61, 0x72, 0x74,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x74,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x72,
	0x74, 0x55, 0x75, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x12, 0x43, 0x61, 0x72, 0x74, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x25, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x61,
	0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x32, 0x97, 0x02, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x74, 0x12, 0x2f, 0x0a, 0x03, 0x47,
	0x65, 0x74, 0x12, 0x10, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x47, 0x65,
	0x74, 0x4d, 0x73, 0x67, 0x1a, 0x16, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x4f, 0x0a, 0x10,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x1d, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4d, 0x73, 0x67, 0x1a,
	0x1c, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x3b, 0x0a,
	0x07, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e,
	0x43, 0x61, 0x72, 0x74, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x73, 0x67, 0x1a, 0x1a,
	0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x50, 0x0a, 0x0e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x2e, 0x63,
	0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x1a, 0x21, 0x2e, 0x63, 0x61, 0x72, 0x74,
	0x2e, 0x43, 0x61, 0x72, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x42, 0x43, 0x0a, 0x08,
	0x66, 0x72, 0x2e, 0x73, 0x65, 0x64, 0x65, 0x6f, 0x50, 0x01, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x64, 0x65, 0x6f, 0x74, 0x65, 0x63, 0x68,
	0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69,
	0x65, 0x77, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cart_cart_proto_rawDescOnce sync.Once
	file_cart_cart_proto_rawDescData = file_cart_cart_proto_rawDesc
)

func file_cart_cart_proto_rawDescGZIP() []byte {
	file_cart_cart_proto_rawDescOnce.Do(func() {
		file_cart_cart_proto_rawDescData = protoimpl.X.CompressGZIP(file_cart_cart_proto_rawDescData)
	})
	return file_cart_cart_proto_rawDescData
}

var file_cart_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_cart_cart_proto_goTypes = []interface{}{
	(*CartMsg)(nil),                     // 0: cart.CartMsg
	(*CartGetMsg)(nil),                  // 1: cart.CartGetMsg
	(*CartGetResultMsg)(nil),            // 2: cart.CartGetResultMsg
	(*CartConfigureAddressMsg)(nil),     // 3: cart.CartConfigureAddressMsg
	(*CartConfigureResultMsg)(nil),      // 4: cart.CartConfigureResultMsg
	(*CartAddItemMsg)(nil),              // 5: cart.CartAddItemMsg
	(*CartAddItemResultMsg)(nil),        // 6: cart.CartAddItemResultMsg
	(*CartUpdateQuantityMsg)(nil),       // 7: cart.CartUpdateQuantityMsg
	(*CartUpdateQuantityResultMsg)(nil), // 8: cart.CartUpdateQuantityResultMsg
	(*CartEmptyMsg)(nil),                // 9: cart.CartEmptyMsg
	(*CartEmptyResultMsg)(nil),          // 10: cart.CartEmptyResultMsg
	(*CartMsg_EntryMsg)(nil),            // 11: cart.CartMsg.EntryMsg
	(*CartMsg_ConfigurationMsg)(nil),    // 12: cart.CartMsg.ConfigurationMsg
	(*timestamppb.Timestamp)(nil),       // 13: google.protobuf.Timestamp
	(*typepb.AddressMsg)(nil),           // 14: type.AddressMsg
	(*itempb.ItemMsg)(nil),              // 15: item.ItemMsg
}
var file_cart_cart_proto_depIdxs = []int32{
	11, // 0: cart.CartMsg.entries:type_name -> cart.CartMsg.EntryMsg
	12, // 1: cart.CartMsg.configuration:type_name -> cart.CartMsg.ConfigurationMsg
	13, // 2: cart.CartMsg.created:type_name -> google.protobuf.Timestamp
	13, // 3: cart.CartMsg.updated:type_name -> google.protobuf.Timestamp
	0,  // 4: cart.CartGetResultMsg.result:type_name -> cart.CartMsg
	14, // 5: cart.CartConfigureAddressMsg.address:type_name -> type.AddressMsg
	0,  // 6: cart.CartConfigureResultMsg.result:type_name -> cart.CartMsg
	0,  // 7: cart.CartAddItemResultMsg.result:type_name -> cart.CartMsg
	0,  // 8: cart.CartUpdateQuantityResultMsg.result:type_name -> cart.CartMsg
	0,  // 9: cart.CartEmptyResultMsg.result:type_name -> cart.CartMsg
	15, // 10: cart.CartMsg.EntryMsg.item:type_name -> item.ItemMsg
	14, // 11: cart.CartMsg.ConfigurationMsg.address:type_name -> type.AddressMsg
	1,  // 12: cart.Cart.Get:input_type -> cart.CartGetMsg
	3,  // 13: cart.Cart.ConfigureAddress:input_type -> cart.CartConfigureAddressMsg
	5,  // 14: cart.Cart.AddItem:input_type -> cart.CartAddItemMsg
	7,  // 15: cart.Cart.UpdateQuantity:input_type -> cart.CartUpdateQuantityMsg
	2,  // 16: cart.Cart.Get:output_type -> cart.CartGetResultMsg
	4,  // 17: cart.Cart.ConfigureAddress:output_type -> cart.CartConfigureResultMsg
	6,  // 18: cart.Cart.AddItem:output_type -> cart.CartAddItemResultMsg
	8,  // 19: cart.Cart.UpdateQuantity:output_type -> cart.CartUpdateQuantityResultMsg
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_cart_cart_proto_init() }
func file_cart_cart_proto_init() {
	if File_cart_cart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cart_cart_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cart_cart_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartGetMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cart_cart_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartGetResultMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cart_cart_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartConfigureAddressMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cart_cart_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartConfigureResultMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cart_cart_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartAddItemMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cart_cart_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartAddItemResultMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cart_cart_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartUpdateQuantityMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cart_cart_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartUpdateQuantityResultMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cart_cart_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartEmptyMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cart_cart_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartEmptyResultMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cart_cart_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartMsg_EntryMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cart_cart_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartMsg_ConfigurationMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cart_cart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cart_cart_proto_goTypes,
		DependencyIndexes: file_cart_cart_proto_depIdxs,
		MessageInfos:      file_cart_cart_proto_msgTypes,
	}.Build()
	File_cart_cart_proto = out.File
	file_cart_cart_proto_rawDesc = nil
	file_cart_cart_proto_goTypes = nil
	file_cart_cart_proto_depIdxs = nil
}
