// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: item/item.proto

package itempb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ItemClient is the client API for Item service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ItemClient interface {
	Create(ctx context.Context, in *ItemCreateMsg, opts ...grpc.CallOption) (*ItemMsg, error)
	Update(ctx context.Context, in *ItemUpdateMsg, opts ...grpc.CallOption) (*ItemMsg, error)
	Delete(ctx context.Context, in *ItemDeleteMsg, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Get(ctx context.Context, in *ItemGetMsg, opts ...grpc.CallOption) (*ItemGetResultMsg, error)
	List(ctx context.Context, in *ItemListMsg, opts ...grpc.CallOption) (*ItemListResultMsg, error)
}

type itemClient struct {
	cc grpc.ClientConnInterface
}

func NewItemClient(cc grpc.ClientConnInterface) ItemClient {
	return &itemClient{cc}
}

func (c *itemClient) Create(ctx context.Context, in *ItemCreateMsg, opts ...grpc.CallOption) (*ItemMsg, error) {
	out := new(ItemMsg)
	err := c.cc.Invoke(ctx, "/item.Item/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemClient) Update(ctx context.Context, in *ItemUpdateMsg, opts ...grpc.CallOption) (*ItemMsg, error) {
	out := new(ItemMsg)
	err := c.cc.Invoke(ctx, "/item.Item/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemClient) Delete(ctx context.Context, in *ItemDeleteMsg, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/item.Item/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemClient) Get(ctx context.Context, in *ItemGetMsg, opts ...grpc.CallOption) (*ItemGetResultMsg, error) {
	out := new(ItemGetResultMsg)
	err := c.cc.Invoke(ctx, "/item.Item/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemClient) List(ctx context.Context, in *ItemListMsg, opts ...grpc.CallOption) (*ItemListResultMsg, error) {
	out := new(ItemListResultMsg)
	err := c.cc.Invoke(ctx, "/item.Item/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemServer is the server API for Item service.
// All implementations must embed UnimplementedItemServer
// for forward compatibility
type ItemServer interface {
	Create(context.Context, *ItemCreateMsg) (*ItemMsg, error)
	Update(context.Context, *ItemUpdateMsg) (*ItemMsg, error)
	Delete(context.Context, *ItemDeleteMsg) (*emptypb.Empty, error)
	Get(context.Context, *ItemGetMsg) (*ItemGetResultMsg, error)
	List(context.Context, *ItemListMsg) (*ItemListResultMsg, error)
	mustEmbedUnimplementedItemServer()
}

// UnimplementedItemServer must be embedded to have forward compatible implementations.
type UnimplementedItemServer struct {
}

func (UnimplementedItemServer) Create(context.Context, *ItemCreateMsg) (*ItemMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedItemServer) Update(context.Context, *ItemUpdateMsg) (*ItemMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedItemServer) Delete(context.Context, *ItemDeleteMsg) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedItemServer) Get(context.Context, *ItemGetMsg) (*ItemGetResultMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedItemServer) List(context.Context, *ItemListMsg) (*ItemListResultMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedItemServer) mustEmbedUnimplementedItemServer() {}

// UnsafeItemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItemServer will
// result in compilation errors.
type UnsafeItemServer interface {
	mustEmbedUnimplementedItemServer()
}

func RegisterItemServer(s grpc.ServiceRegistrar, srv ItemServer) {
	s.RegisterService(&Item_ServiceDesc, srv)
}

func _Item_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemCreateMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.Item/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServer).Create(ctx, req.(*ItemCreateMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Item_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemUpdateMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.Item/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServer).Update(ctx, req.(*ItemUpdateMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Item_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemDeleteMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.Item/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServer).Delete(ctx, req.(*ItemDeleteMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Item_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemGetMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.Item/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServer).Get(ctx, req.(*ItemGetMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Item_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemListMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.Item/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServer).List(ctx, req.(*ItemListMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// Item_ServiceDesc is the grpc.ServiceDesc for Item service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Item_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "item.Item",
	HandlerType: (*ItemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Item_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Item_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Item_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Item_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Item_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item/item.proto",
}
